# Generated by Django 4.1.10 on 2024-03-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30, verbose_name='Имя')),
                ('LastName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTest', models.CharField(max_length=50, verbose_name='Название теста')),
                ('DescriptionTest', models.TextField(blank=True, verbose_name='Описание теста')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextQuestion', models.TextField(verbose_name='Текст вопроса')),
                ('ImageQuestion', models.ImageField(blank=True, default=None, null=True, upload_to='_/%Y/%m/%d/', verbose_name='Картинка вопроса')),
                ('TestNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.employeestest', verbose_name='Номер теста')),
            ],
        ),
        migrations.CreateModel(
            name='NominatedTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarksTest', models.SmallIntegerField(verbose_name='Оценка за тест')),
                ('DateTimePassing', models.DateTimeField(verbose_name='Дата/время прохождения теста')),
                ('TravelTime', models.DateTimeField(verbose_name='Время прохождения теста')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.employees', verbose_name='Сотрудник')),
                ('Test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.employeestest', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextAnswer', models.TextField(verbose_name='Текст ответа')),
                ('MarkAnswer', models.SmallIntegerField(verbose_name='Количество баллов за ответ')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.questions', verbose_name='Ответ на вопрос')),
            ],
        ),
    ]
