# Generated by Django 4.1.10 on 2024-03-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestions',
            options={'verbose_name': 'ответы на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='employeestest',
            options={'verbose_name': 'тест сотрудников', 'verbose_name_plural': 'Тесты сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'вопрос теста', 'verbose_name_plural': 'Вопросы теста'},
        ),
        migrations.AlterField(
            model_name='answerquestions',
            name='MarkAnswer',
            field=models.SmallIntegerField(default=0, verbose_name='Количество баллов за ответ'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
    ]
